name = "synnovator"
main = "./dist/_worker.js/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist"

[vars]
SITE_URL = "https://home.synnovator.space"
GITHUB_CLIENT_ID = "Iv23liQaa34mwXMU912V"
GITHUB_OWNER = "Synnovator"
GITHUB_REPO = "monorepo"
