synnovator_submission: "2.0"
project:
  name: "我的黑历史"
  name_zh: "测试项目"
  tagline: "testing"
  track: "ai-application"
  team_ref: "team-project"
  deliverables:
    repo: "https://github.com/CS571-F23/hw12-Cynthialime"
  tech_stack:
    - "python"